development:
  adapter: mysql
  database: example
  username: root
  password: tiger
  host: localhost
test:
  adapter: mysql
  database: library_test
  username: root
  password: tiger
  host: localhost
production:
  adapter: mysql
  database: library_production
  username: root
  password: tiger
  host: localhost
